title: Phu Huy Tran
logo: https://github.com/huyphutran/huyphutran.github.io/assets/49059492/55058d6a-fb9f-405f-9371-60f23644f2ba/headshot_circle.png

#description: text below image
show_downloads: true
theme: jekyll-theme-minimal
